const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync('index.html', 'utf8');
const sw = fs.readFileSync('sw.js', 'utf8');

assert(html.includes('id="firstRunSplash"'));
assert(html.includes('name="description"'));
assert(html.includes('href="#main-content"'));
assert(html.includes('id="main-content"'));
assert(html.includes('class="skip-link"'));
assert(html.includes('id="firstRunOnboarding"'));
assert(html.includes('src="icon.png"'));
assert(!html.includes('apiBaseInput'));
assert(!html.includes('splash-footer'));
assert(html.includes("/api/announcements"));
assert(html.includes("/api/announcements/${encodeURIComponent(id)}/read"));
assert(html.includes('/api/streak/activity'));
assert(html.includes('/api/quotes/daily?date='));
assert(html.includes('function loadDailyQuote()'));
assert(html.includes('DAILY_QUOTES_FALLBACK'));
assert(html.includes('function scheduleDailyRefresh()'));
assert(html.includes('function toggleTheme()'));
assert(html.includes('const GREETING_OPTIONS'));
assert(html.includes("period = hour >= 5 && hour < 12"));
assert(html.includes("night: ['Hello night owl'"));
assert(html.includes('id="mobileGreeting"'));
assert(html.includes('function renderGreeting()'));
assert(html.includes("if (mobile) mobile.textContent"));
assert(html.includes('id="focusCard"'));
assert(html.includes('function toggleFocusTimer()'));
assert(html.includes("recordStudyActivity('focus_session')"));
assert(html.includes('Short break'));
assert(html.includes('id="dailyPlanCard"'));
assert(html.includes('function renderDailyPlan()'));
assert(html.includes('function startFocusFromPlan(courseId)'));
assert(html.includes('data-plan-action'));
assert(html.includes("const STUDY_ACTIVITY_QUEUE_KEY"));
assert(html.includes('function flushPendingStudyActivity()'));
assert(html.includes("window.addEventListener('online', flushPendingStudyActivity)"));
assert(html.includes('id="settingsReminderTime"'));
assert(html.includes('id="settingsQuietStart"'));
assert(html.includes('function isQuietHours('));
assert(html.includes('function maybeShowSmartReminder()'));
assert(html.includes('themeInteractionVersion'));
assert(html.includes('.dark .study-quote-card'));
assert(html.includes('currentStreak: data.currentStreak'));
assert(html.includes("/api/auth/logout"));
assert(html.includes("credentials: 'include'"));
assert(sw.includes("const CACHE_NAME = 'eduflow-shell-v3'"));
assert(sw.includes("'./icon.png'"));
console.log('EduFlow frontend contract smoke test: PASS');
