const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync('index.html', 'utf8');
const sw = fs.readFileSync('sw.js', 'utf8');
const baseCss = fs.readFileSync('assets/css/base.css', 'utf8');
const componentsCss = fs.readFileSync('assets/css/components.css', 'utf8');
const themeCss = fs.readFileSync('assets/css/theme.css', 'utf8');
const domUtils = fs.readFileSync('assets/js/utils/dom.js', 'utf8');
const formattingUtils = fs.readFileSync('assets/js/utils/formatting.js', 'utf8');
const uiUtils = fs.readFileSync('assets/js/utils/ui.js', 'utf8');
const apiClient = fs.readFileSync('assets/js/api/client.js', 'utf8');
const stateStore = fs.readFileSync('assets/js/state/store.js', 'utf8');
const coursesFeature = fs.readFileSync('assets/js/features/courses.js', 'utf8');
const assignmentsFeature = fs.readFileSync('assets/js/features/assignments.js', 'utf8');
const timetableFeature = fs.readFileSync('assets/js/features/timetable.js', 'utf8');

assert(html.includes('id="firstRunSplash"'));
assert(html.includes('name="description"'));
assert(html.includes('href="#main-content"'));
assert(html.includes('id="main-content"'));
assert(html.includes('class="skip-link"'));
assert(html.includes('id="firstRunOnboarding"'));
assert(html.includes('src="icon.png"'));
assert(!html.includes('apiBaseInput'));
assert(!html.includes('splash-footer'));
assert(html.includes('href="assets/css/base.css"'));
assert(html.includes('href="assets/css/components.css"'));
assert(html.includes('href="assets/css/theme.css"'));
assert(!html.includes('<style>'));
assert(baseCss.includes('html { scroll-behavior: smooth; }'));
assert(componentsCss.includes('.mobile-hero-toolbar'));
assert(themeCss.length > 1000);
assert(html.includes('src="assets/js/utils/dom.js"'));
assert(html.includes('src="assets/js/utils/formatting.js"'));
assert(html.includes('src="assets/js/utils/ui.js"'));
assert(domUtils.includes('function qs(sel, root)'));
assert(domUtils.includes('function qsa(sel, root)'));
assert(formattingUtils.includes('function escapeHtml(str)'));
assert(uiUtils.includes('function showToast(message)'));
assert(html.includes('src="assets/js/api/client.js"'));
assert(html.includes('src="assets/js/state/store.js"'));
assert(apiClient.includes('async function apiFetch(path, options)'));
assert(apiClient.includes("credentials: 'include'"));
assert(stateStore.includes('const state = {'));
assert(stateStore.includes('quiet_hours_start'));
assert(html.includes('src="assets/js/features/courses.js"'));
assert(coursesFeature.includes('async function addCourse(e)'));
assert(coursesFeature.includes('function renderCourses()'));
assert(coursesFeature.includes('function populateCourseSelects()'));
assert(!html.includes('/* ================= COURSES ================= */'));
assert(html.includes('src="assets/js/features/assignments.js"'));
assert(assignmentsFeature.includes('async function addAssignment(e)'));
assert(assignmentsFeature.includes('function renderAssignments()'));
assert(assignmentsFeature.includes('function initAssignmentFilters()'));
assert(!html.includes('/* ================= ASSIGNMENTS ================= */'));
assert(html.includes('src="assets/js/features/timetable.js"'));
assert(timetableFeature.includes('async function addClass(e)'));
assert(timetableFeature.includes('function renderTimetable()'));
assert(!html.includes('/* ================= TIMETABLE ================= */'));
assert(html.includes("/api/announcements"));
assert(html.includes("/api/announcements/${encodeURIComponent(id)}/read"));
assert(html.includes('/api/streak/activity'));
assert(html.includes('/api/quotes/daily?date='));
assert(html.includes('function loadDailyQuote()'));
assert(html.includes('DAILY_QUOTES_FALLBACK'));
assert(html.includes('function scheduleDailyRefresh()'));
assert(html.includes('function toggleTheme()'));
assert(html.includes('const GREETING_OPTIONS'));
assert(html.includes("period = hour >= 5 && hour < 12"));
assert(html.includes("night: ['Hello night owl'"));
assert(html.includes('id="mobileGreeting"'));
assert(html.includes('function renderGreeting()'));
assert(html.includes("if (mobile) mobile.textContent"));
assert(html.includes('id="focusCard"'));
assert(html.includes('function toggleFocusTimer()'));
assert(html.includes("recordStudyActivity('focus_session')"));
assert(html.includes('Short break'));
assert(html.includes('id="dailyPlanCard"'));
assert(html.includes('function renderDailyPlan()'));
assert(html.includes('function startFocusFromPlan(courseId)'));
assert(html.includes('data-plan-action'));
assert(html.includes("const STUDY_ACTIVITY_QUEUE_KEY"));
assert(html.includes('function flushPendingStudyActivity()'));
assert(html.includes("window.addEventListener('online', flushPendingStudyActivity)"));
assert(html.includes('id="settingsReminderTime"'));
assert(html.includes('id="settingsQuietStart"'));
assert(html.includes('function isQuietHours('));
assert(html.includes('function maybeShowSmartReminder()'));
assert(html.includes('id="courseHealthCard"'));
assert(html.includes('function courseHealth(course)'));
assert(html.includes('function renderCourseHealth()'));
assert(html.includes('data-health-course'));
assert(html.includes('themeInteractionVersion'));
assert(componentsCss.includes('.dark .study-quote-card'));
assert(html.includes('currentStreak: data.currentStreak'));
assert(html.includes("/api/auth/logout"));
assert(apiClient.includes("credentials: 'include'"));
assert(sw.includes("const CACHE_NAME = 'eduflow-shell-v3'"));
assert(sw.includes("'./icon.png'"));
console.log('EduFlow frontend contract smoke test: PASS');
